### ISSUE TITLE
3.1.4 regression. Crash on missing uv property

### ISSUE THREAD

**Issue by altavir** [samalexander/three-csg-ts#33]
The same as #2 again.

**Comment by manthrax** [comment]
@altavir working on it...

**Comment by samalexander** [comment]
Fix released in v3.1.5

**Comment by altavir** [comment]
Does not seem to fix the problem. The problem is in those lines: https://github.com/Jiro-Digital/three-csg-ts/blob/70b6258138e513719b563dc8bfb326e379d0a7d4/src/CSG.ts#L58-L59. If the input geometry does not define uvs, it crashes. Please reopen.
